language: node_js
node_js:
  - 13

before_script:
  - yarn run setup
  - yarn run build

script:
  - yarn run test

after_success:
  - yarn run typedoc

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
  - provider: yarn
    skip_cleanup: true
    email: 'mcoquand@gmail.com'
    api_key: $NPM_TOKEN
    on:
      tags: true
